### ISSUE TITLE
Not an issue, but a question about the files 

### ISSUE THREAD

**Issue by RasArtGhul** [alastair-duncan/SuperEZGraver#1]
Hello. 
So, I got suggested this project by someone I'm talking to, and I am a huge fan of all the work you put in. 
However, I had some issues with some of the parts being way too large and loose when printed on my printer(maybe the printer you used to print yours was less dimensionally accurate, I don't know, it doesn't matter). 
So I took your original model and re-created it in Fusion 360 and adjusted it until all the parts fit together well when I printed it. 

Are you okay with me uploading the Fusion 360 and the STEP files as well as my versions of the STLs? I would upload them as pull requests here on Github, but I wanted to ask you first :-)

**Comment by alastair-duncan** [comment]
Hi Anarsha,

I'd be happy to have the additions, a pull request is fine, if you could add a readme to describe what and why so that others may benefit that would be great.

Thank you
