### ISSUE TITLE
Separate PWM needed?

### ISSUE THREAD

**Issue by ps-bond** [alastair-duncan/SuperEZGraver#3]
Given the Arduino can directly output PWM to the MOSFET, can I ask what the design decison is to use an external PWM from the MOSFET?  I may have missed something., of course.
(And is there really no option to set this as a low prio issue???)

**Comment by alastair-duncan** [comment]
The PWM output from the arduino is 5v and the max current is limited to what the board can handle(50mA if I remember correctly) The PWM output from the external PWM is 6-60v and the max current is 30A - limited by the power supply that is connected.

I'm not an electronics engineer so there may be a way to do this with the arduino controlling the pwm. I wanted to be able to put together a system from off the shelf components that kept the complexity of the electronics and code to a minimum.

**Comment by ps-bond** [comment]
I'll sit down and scribble some calculations - the code shouldn't get much more complex, just need to watch out for duty cycle on the solenoid to stop it overheating.  If I'm right, it'll knock the cost down some more.  Will feed back to you.

Embedded software engineer & jeweller, depending on day of the week :)

**Comment by ps-bond** [comment]
Now tested (using an ESP8266 and microPython - not critical, it can be tweaked to other boards) and yes, PWM does work as might be expected.  In addition to the solenoid, I've got a FET module, a diode and the microcontroller (and an inexpensive 12V PSU).  Only a command line test program at the moment, but it allows me to play with settings easily.

**Comment by alastair-duncan** [comment]
Thanks, I'll take a look at what you have done, get some bits and have a play myself. I've not come across the ESP8266 board but it looks very interesting and the use of python is nice.

**Comment by ps-bond** [comment]
The ESP8266 is overkill (Wifi enabled gravers?) but it was the first board I grabbed - it'll also run on a number of other boards (including the Pi Pico, for example - £3.60).  MicroPython allows for a quick & easy approach on tweaking development, but it does have some downsides (it runs out of memory quickly because it's doing so much more than a simple compiled program).  

I have an idea or two on touchscreen UIs; undecided if I'll switch to C++ for that.  Or C, doesn't really matter which :)

Not done yet...  Oh, and I've been tweaking readmes a little as well.  And my handpiece - based on yours - doesn't need the brass insert.

Almost forgot - it's all in the python_dev branch.

**Comment by alastair-duncan** [comment]
There is a module that will do all of the signal generation  and controlling of the duty cycle but the interface to it is really poor.

https://www.ebay.co.uk/itm/192338137447

It has a serial interface but this is really flaky you can poke it once( I used the Arduino to do this) and change the settings but it requires a hard reset to be able to do it again. Its a shame because it has a display and apart from a poor interface it works really well.

**Comment by ps-bond** [comment]
Aside from the peak frequency, I'm not sure that gives much more than the uC PWM output offers (and it's much easier to fettle the output behaviour).

If it's a display you want - http://www.lilygo.cn/prod_view.aspx?TypeId=50044&Id=1126&FId=t3:50044:3 
(Still an overkill microcontroller!)

**Comment by alastair-duncan** [comment]
I like being able to see the power output at a glance. It's not going to be
a complete view of power as the stroke length also has an impact on the
power of the strike. Is it really important? Probably not as I do some test
cuts to see how it feels before doing any cuts that count.

I looked at the signal generator a while ago to see if there were better
solutions to what I had.

**Comment by ps-bond** [comment]
Next version I'll incorporate a simple display - I might have to rethink my threading approach as it's not fully supported on microPython.  If it does what I want, fine; if not, I'll fall back to a simpler approach.

I vary stroke length according to what I'm doing with the Airgraver too.
